# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               PK
tagline:             'Blog'
description:         '12 Weeks Journey into Data Science'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              PK
  url:               https://nwupkc.github.io
  email:             nwupkc@gmail.com

plugins: [jekyll-paginate]
markdown: kramdown
