# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               PK
tagline:             'Blog'
description:         '12 Weeks Journey into Data Science'
url:                 https://nwupkc.github.io
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              PK
  url:               https://nwupkc.github.io

plugins: [jekyll-paginate]
markdown: kramdown
