# Permalinks
permalink:           pretty

# Setup
title:               pk
url:                 https://nwupkc.github.io

# About/contact
author:
  name:              PK
  url:               https://nwupkc.github.io

plugins: [jekyll-paginate]
markdown: kramdown
